<div class="footer-top">
		<div class="container">
			<div class="col-md-3 w3ls-footer-top">
				<h3>QUICK <span>LINKS</span></h3>
					<ul>
							<li><a href="index.php">Home</a></li>
							<li><a href="about.php">About</a></li>
							<li><a href="services.php">Services</a></li>
							<li><a href="modules.php">Modules</a></li>
							<li><a href="project.php">Projects</a></li>
							<li><a href="contact.php">Contact</a></li>
						</ul>
			</div>
			<div class="col-md-4 wthree-footer-top">
				<h3>ADD<span>RESS</span></h3>
					<ul>
					<li><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Old Post Office Road Samastripur,BIHAR-848101,INDIA </li>
					<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:info@example.com">info@omnisun.co.in</a></li>
					<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+91 8298555501,+91 778193412</li>
				</ul>
			</div>
			
			<div class="col-md-5 w3l-footer-top">
				<h3>ABOUT<span> US</span></h3>
				<p>A solar-powered pump is a pump running on electricity generated by photovoltaic panels or the radiated thermal energy available from collected sunlight as opposed to grid electricity or diesel run water pumps</p>

					<form action="#" method="post" class="newsletter">
						<input class="email" type="email" placeholder="Your email..." required="">
						<input type="submit" class="submit"  value="">
					</form>
			</div>
				<div class="clearfix"></div>
			<div class="footer-w3layouts">
				<div class="agile-copy">
					<p>© 2018 OMNISUNS Solar Panel. All rights reserved | Design by <a href="https://www.domainindia.org/">DOMAIN REGISTRATION INDIA PRIVATE LIMITED</a></p>
				</div>
			</div>
		</div>
	</div>