  <footer>
        <div class="container">
            <div class="row footer-top-w3layouts">
                <div class="col-lg-3 footer-grid-w3ls" data-aos="zoom-in">
                    <div class="footer-title">
                        <h2>About Us</h2>
                    </div>
                    <div class="footer-text">
                        <p>A solar-powered pump is a pump running on electricity generated by photovoltaic panels or the radiated thermal energy available from collected sunlight as opposed to grid electricity or diesel run water pumps</p>

                    </div>
                </div>
                <div class="col-lg-3 footer-grid-w3ls" data-aos="zoom-in">
                    <div class="footer-title">
                        <h3>Contact Us</h3>
                    </div>
                    <div class="footer-office-hour">
                        <ul>
                            <li class="hd">Address :</li>
                            <li>Old Post Office Road</li>
                            <li>Near Anil complex,Samastripur,</li>
                            <li>BIHAR-848101,INDIA</li>
                           

                        </ul>
                        <ul>
                            <li class="hd">Phone: <p>+91 8298555501,+91 778193412</p></li>
                           
                            <li class="hd">Fax: 1(234) 567 8901</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 footer-grid-w3ls" data-aos="zoom-in">
                    <div class="footer-title">
                        <h3>Recent Works</h3>
                    </div>
                    <div class="footer-list">
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w1.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w2.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w3.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w4.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w5.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w6.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <!--<div class="flickr-grid">
                            <a href="single.php">
                                <img src="images/w6.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>-->
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w7.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="flickr-grid">
                            <a href="#">
                                <img src="images/w8.jpg" class="img-fluid" alt=" ">
                            </a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="col-lg-3 footer-grid-w3ls" data-aos="zoom-in">
                    <div class="footer-title">
                        <h3>Subscribe</h3>
                    </div>
                    <p>OMNISUN Energy is positioned to meet the chanllenges of the rapidly growing solar market.</p>
                    <form action="#" method="post" class="newsletter">
                        <input class="email" type="email" placeholder="Your email..." required="">
                        <button class="btn1">
                            <i class="far fa-envelope"></i>
                        </button>
                    </form>
                    <div class="clearfix"></div>
                </div>

    </footer>


      <div class="copyright">
        <div class="container">
            <div class="copyrighttop" data-aos="fade-left">
                <ul>
                    <li>
                        <h4>Follow us on:</h4>
                    </li>
                    <li>
                        <a class="facebook" href="#">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li>
                        <a class="facebook" href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a class="facebook" href="#">
                            <i class="fab fa-google-plus-g"></i>
                        </a>
                    </li>
                    <li>
                        <a class="facebook" href="#">
                            <i class="fab fa-pinterest-p"></i>
                        </a>
                    </li>
                </ul>
            </div>
           <div class="copyrightbottom">
            <p>© 2019 OMNISUNC.All Rights Reserved | Design By <a href="https://www.domainindia.org/">
            DOMAIN REGISTRATION INDIA PRIVATE LIMITED</a></p>
        </div>
            
           
            <div class="clearfix"></div>
        </div>
    </div>
